mongo-container:
  image: mongo:3.4
  container_name: mongodb
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD="{ROOT_PASSWORD}"
  ports:
    - "27017:27017"
  volumes:
    - "./db:/data/db"
    - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  command: mongod