es:
  image: elasticsearch:6.5.0
  container_name: es
  restart: always
  environment:
    - node.name=es
    - cluster.name=es-docker-cluster
    - http.cors.enabled=true
    - http.cors.allow-origin="*"
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - data:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300
